project_name: ctRestClient
builds:
  - id: linux-amd64
    main: ./main.go
    binary: ctRestClient-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
  - id: darwin-amd64
    main: ./main.go
    binary: ctRestClient-darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
  - id: darwin-arm64
    main: ./main.go
    binary: ctRestClient-darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
  - id: windows-amd64
    main: ./main.go
    binary: ctRestClient-windows-amd64
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
archives:
  - id: platform-specific
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - '^refactor:'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: mvach
    name: ctRestClient