// Code generated by counterfeiter. DO NOT EDIT.
package appfakes

import (
	"ctRestClient/app"
	"ctRestClient/rest"
	"encoding/json"
	"sync"
)

type FakeGroupExporter struct {
	ExportPersonDataStub        func(string, rest.DynamicGroupsEndpoint, rest.GroupsEndpoint, rest.PersonsEndpoint) ([]json.RawMessage, error)
	exportPersonDataMutex       sync.RWMutex
	exportPersonDataArgsForCall []struct {
		arg1 string
		arg2 rest.DynamicGroupsEndpoint
		arg3 rest.GroupsEndpoint
		arg4 rest.PersonsEndpoint
	}
	exportPersonDataReturns struct {
		result1 []json.RawMessage
		result2 error
	}
	exportPersonDataReturnsOnCall map[int]struct {
		result1 []json.RawMessage
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGroupExporter) ExportPersonData(arg1 string, arg2 rest.DynamicGroupsEndpoint, arg3 rest.GroupsEndpoint, arg4 rest.PersonsEndpoint) ([]json.RawMessage, error) {
	fake.exportPersonDataMutex.Lock()
	ret, specificReturn := fake.exportPersonDataReturnsOnCall[len(fake.exportPersonDataArgsForCall)]
	fake.exportPersonDataArgsForCall = append(fake.exportPersonDataArgsForCall, struct {
		arg1 string
		arg2 rest.DynamicGroupsEndpoint
		arg3 rest.GroupsEndpoint
		arg4 rest.PersonsEndpoint
	}{arg1, arg2, arg3, arg4})
	stub := fake.ExportPersonDataStub
	fakeReturns := fake.exportPersonDataReturns
	fake.recordInvocation("ExportPersonData", []interface{}{arg1, arg2, arg3, arg4})
	fake.exportPersonDataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupExporter) ExportPersonDataCallCount() int {
	fake.exportPersonDataMutex.RLock()
	defer fake.exportPersonDataMutex.RUnlock()
	return len(fake.exportPersonDataArgsForCall)
}

func (fake *FakeGroupExporter) ExportPersonDataCalls(stub func(string, rest.DynamicGroupsEndpoint, rest.GroupsEndpoint, rest.PersonsEndpoint) ([]json.RawMessage, error)) {
	fake.exportPersonDataMutex.Lock()
	defer fake.exportPersonDataMutex.Unlock()
	fake.ExportPersonDataStub = stub
}

func (fake *FakeGroupExporter) ExportPersonDataArgsForCall(i int) (string, rest.DynamicGroupsEndpoint, rest.GroupsEndpoint, rest.PersonsEndpoint) {
	fake.exportPersonDataMutex.RLock()
	defer fake.exportPersonDataMutex.RUnlock()
	argsForCall := fake.exportPersonDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGroupExporter) ExportPersonDataReturns(result1 []json.RawMessage, result2 error) {
	fake.exportPersonDataMutex.Lock()
	defer fake.exportPersonDataMutex.Unlock()
	fake.ExportPersonDataStub = nil
	fake.exportPersonDataReturns = struct {
		result1 []json.RawMessage
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupExporter) ExportPersonDataReturnsOnCall(i int, result1 []json.RawMessage, result2 error) {
	fake.exportPersonDataMutex.Lock()
	defer fake.exportPersonDataMutex.Unlock()
	fake.ExportPersonDataStub = nil
	if fake.exportPersonDataReturnsOnCall == nil {
		fake.exportPersonDataReturnsOnCall = make(map[int]struct {
			result1 []json.RawMessage
			result2 error
		})
	}
	fake.exportPersonDataReturnsOnCall[i] = struct {
		result1 []json.RawMessage
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupExporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.exportPersonDataMutex.RLock()
	defer fake.exportPersonDataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGroupExporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ app.GroupExporter = new(FakeGroupExporter)
