// Code generated by counterfeiter. DO NOT EDIT.
package restfakes

import (
	"ctRestClient/internal/rest"
	"sync"
)

type FakeGroupEndpoint struct {
	GetGroupTypeStub        func(int) (rest.GroupTypeResponse, error)
	getGroupTypeMutex       sync.RWMutex
	getGroupTypeArgsForCall []struct {
		arg1 int
	}
	getGroupTypeReturns struct {
		result1 rest.GroupTypeResponse
		result2 error
	}
	getGroupTypeReturnsOnCall map[int]struct {
		result1 rest.GroupTypeResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGroupEndpoint) GetGroupType(arg1 int) (rest.GroupTypeResponse, error) {
	fake.getGroupTypeMutex.Lock()
	ret, specificReturn := fake.getGroupTypeReturnsOnCall[len(fake.getGroupTypeArgsForCall)]
	fake.getGroupTypeArgsForCall = append(fake.getGroupTypeArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetGroupTypeStub
	fakeReturns := fake.getGroupTypeReturns
	fake.recordInvocation("GetGroupType", []interface{}{arg1})
	fake.getGroupTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupEndpoint) GetGroupTypeCallCount() int {
	fake.getGroupTypeMutex.RLock()
	defer fake.getGroupTypeMutex.RUnlock()
	return len(fake.getGroupTypeArgsForCall)
}

func (fake *FakeGroupEndpoint) GetGroupTypeCalls(stub func(int) (rest.GroupTypeResponse, error)) {
	fake.getGroupTypeMutex.Lock()
	defer fake.getGroupTypeMutex.Unlock()
	fake.GetGroupTypeStub = stub
}

func (fake *FakeGroupEndpoint) GetGroupTypeArgsForCall(i int) int {
	fake.getGroupTypeMutex.RLock()
	defer fake.getGroupTypeMutex.RUnlock()
	argsForCall := fake.getGroupTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGroupEndpoint) GetGroupTypeReturns(result1 rest.GroupTypeResponse, result2 error) {
	fake.getGroupTypeMutex.Lock()
	defer fake.getGroupTypeMutex.Unlock()
	fake.GetGroupTypeStub = nil
	fake.getGroupTypeReturns = struct {
		result1 rest.GroupTypeResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupEndpoint) GetGroupTypeReturnsOnCall(i int, result1 rest.GroupTypeResponse, result2 error) {
	fake.getGroupTypeMutex.Lock()
	defer fake.getGroupTypeMutex.Unlock()
	fake.GetGroupTypeStub = nil
	if fake.getGroupTypeReturnsOnCall == nil {
		fake.getGroupTypeReturnsOnCall = make(map[int]struct {
			result1 rest.GroupTypeResponse
			result2 error
		})
	}
	fake.getGroupTypeReturnsOnCall[i] = struct {
		result1 rest.GroupTypeResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGroupEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rest.GroupEndpoint = new(FakeGroupEndpoint)
