// Code generated by counterfeiter. DO NOT EDIT.
package restendpointsfakes

import (
	"ctRestClient/restendpoints"
	"sync"
)

type FakeDynamicGroupsEndpoint struct {
	GetDynamicGroupIdsStub        func() ([]int, error)
	getDynamicGroupIdsMutex       sync.RWMutex
	getDynamicGroupIdsArgsForCall []struct {
	}
	getDynamicGroupIdsReturns struct {
		result1 []int
		result2 error
	}
	getDynamicGroupIdsReturnsOnCall map[int]struct {
		result1 []int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDynamicGroupsEndpoint) GetDynamicGroupIds() ([]int, error) {
	fake.getDynamicGroupIdsMutex.Lock()
	ret, specificReturn := fake.getDynamicGroupIdsReturnsOnCall[len(fake.getDynamicGroupIdsArgsForCall)]
	fake.getDynamicGroupIdsArgsForCall = append(fake.getDynamicGroupIdsArgsForCall, struct {
	}{})
	stub := fake.GetDynamicGroupIdsStub
	fakeReturns := fake.getDynamicGroupIdsReturns
	fake.recordInvocation("GetDynamicGroupIds", []interface{}{})
	fake.getDynamicGroupIdsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDynamicGroupsEndpoint) GetDynamicGroupIdsCallCount() int {
	fake.getDynamicGroupIdsMutex.RLock()
	defer fake.getDynamicGroupIdsMutex.RUnlock()
	return len(fake.getDynamicGroupIdsArgsForCall)
}

func (fake *FakeDynamicGroupsEndpoint) GetDynamicGroupIdsCalls(stub func() ([]int, error)) {
	fake.getDynamicGroupIdsMutex.Lock()
	defer fake.getDynamicGroupIdsMutex.Unlock()
	fake.GetDynamicGroupIdsStub = stub
}

func (fake *FakeDynamicGroupsEndpoint) GetDynamicGroupIdsReturns(result1 []int, result2 error) {
	fake.getDynamicGroupIdsMutex.Lock()
	defer fake.getDynamicGroupIdsMutex.Unlock()
	fake.GetDynamicGroupIdsStub = nil
	fake.getDynamicGroupIdsReturns = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) GetDynamicGroupIdsReturnsOnCall(i int, result1 []int, result2 error) {
	fake.getDynamicGroupIdsMutex.Lock()
	defer fake.getDynamicGroupIdsMutex.Unlock()
	fake.GetDynamicGroupIdsStub = nil
	if fake.getDynamicGroupIdsReturnsOnCall == nil {
		fake.getDynamicGroupIdsReturnsOnCall = make(map[int]struct {
			result1 []int
			result2 error
		})
	}
	fake.getDynamicGroupIdsReturnsOnCall[i] = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getDynamicGroupIdsMutex.RLock()
	defer fake.getDynamicGroupIdsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDynamicGroupsEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ restendpoints.DynamicGroupsEndpoint = new(FakeDynamicGroupsEndpoint)
