// Code generated by counterfeiter. DO NOT EDIT.
package restendpointsfakes

import (
	"ctRestClient/restendpoints"
	"sync"
)

type FakeGroupsEndpoint struct {
	GetGroupMembersStub        func(int) ([]restendpoints.GroupsMembersResponse, error)
	getGroupMembersMutex       sync.RWMutex
	getGroupMembersArgsForCall []struct {
		arg1 int
	}
	getGroupMembersReturns struct {
		result1 []restendpoints.GroupsMembersResponse
		result2 error
	}
	getGroupMembersReturnsOnCall map[int]struct {
		result1 []restendpoints.GroupsMembersResponse
		result2 error
	}
	GetGroupNameStub        func(int) ([]restendpoints.GroupsResponse, error)
	getGroupNameMutex       sync.RWMutex
	getGroupNameArgsForCall []struct {
		arg1 int
	}
	getGroupNameReturns struct {
		result1 []restendpoints.GroupsResponse
		result2 error
	}
	getGroupNameReturnsOnCall map[int]struct {
		result1 []restendpoints.GroupsResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGroupsEndpoint) GetGroupMembers(arg1 int) ([]restendpoints.GroupsMembersResponse, error) {
	fake.getGroupMembersMutex.Lock()
	ret, specificReturn := fake.getGroupMembersReturnsOnCall[len(fake.getGroupMembersArgsForCall)]
	fake.getGroupMembersArgsForCall = append(fake.getGroupMembersArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetGroupMembersStub
	fakeReturns := fake.getGroupMembersReturns
	fake.recordInvocation("GetGroupMembers", []interface{}{arg1})
	fake.getGroupMembersMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupsEndpoint) GetGroupMembersCallCount() int {
	fake.getGroupMembersMutex.RLock()
	defer fake.getGroupMembersMutex.RUnlock()
	return len(fake.getGroupMembersArgsForCall)
}

func (fake *FakeGroupsEndpoint) GetGroupMembersCalls(stub func(int) ([]restendpoints.GroupsMembersResponse, error)) {
	fake.getGroupMembersMutex.Lock()
	defer fake.getGroupMembersMutex.Unlock()
	fake.GetGroupMembersStub = stub
}

func (fake *FakeGroupsEndpoint) GetGroupMembersArgsForCall(i int) int {
	fake.getGroupMembersMutex.RLock()
	defer fake.getGroupMembersMutex.RUnlock()
	argsForCall := fake.getGroupMembersArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGroupsEndpoint) GetGroupMembersReturns(result1 []restendpoints.GroupsMembersResponse, result2 error) {
	fake.getGroupMembersMutex.Lock()
	defer fake.getGroupMembersMutex.Unlock()
	fake.GetGroupMembersStub = nil
	fake.getGroupMembersReturns = struct {
		result1 []restendpoints.GroupsMembersResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) GetGroupMembersReturnsOnCall(i int, result1 []restendpoints.GroupsMembersResponse, result2 error) {
	fake.getGroupMembersMutex.Lock()
	defer fake.getGroupMembersMutex.Unlock()
	fake.GetGroupMembersStub = nil
	if fake.getGroupMembersReturnsOnCall == nil {
		fake.getGroupMembersReturnsOnCall = make(map[int]struct {
			result1 []restendpoints.GroupsMembersResponse
			result2 error
		})
	}
	fake.getGroupMembersReturnsOnCall[i] = struct {
		result1 []restendpoints.GroupsMembersResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) GetGroupName(arg1 int) ([]restendpoints.GroupsResponse, error) {
	fake.getGroupNameMutex.Lock()
	ret, specificReturn := fake.getGroupNameReturnsOnCall[len(fake.getGroupNameArgsForCall)]
	fake.getGroupNameArgsForCall = append(fake.getGroupNameArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetGroupNameStub
	fakeReturns := fake.getGroupNameReturns
	fake.recordInvocation("GetGroupName", []interface{}{arg1})
	fake.getGroupNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupsEndpoint) GetGroupNameCallCount() int {
	fake.getGroupNameMutex.RLock()
	defer fake.getGroupNameMutex.RUnlock()
	return len(fake.getGroupNameArgsForCall)
}

func (fake *FakeGroupsEndpoint) GetGroupNameCalls(stub func(int) ([]restendpoints.GroupsResponse, error)) {
	fake.getGroupNameMutex.Lock()
	defer fake.getGroupNameMutex.Unlock()
	fake.GetGroupNameStub = stub
}

func (fake *FakeGroupsEndpoint) GetGroupNameArgsForCall(i int) int {
	fake.getGroupNameMutex.RLock()
	defer fake.getGroupNameMutex.RUnlock()
	argsForCall := fake.getGroupNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGroupsEndpoint) GetGroupNameReturns(result1 []restendpoints.GroupsResponse, result2 error) {
	fake.getGroupNameMutex.Lock()
	defer fake.getGroupNameMutex.Unlock()
	fake.GetGroupNameStub = nil
	fake.getGroupNameReturns = struct {
		result1 []restendpoints.GroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) GetGroupNameReturnsOnCall(i int, result1 []restendpoints.GroupsResponse, result2 error) {
	fake.getGroupNameMutex.Lock()
	defer fake.getGroupNameMutex.Unlock()
	fake.GetGroupNameStub = nil
	if fake.getGroupNameReturnsOnCall == nil {
		fake.getGroupNameReturnsOnCall = make(map[int]struct {
			result1 []restendpoints.GroupsResponse
			result2 error
		})
	}
	fake.getGroupNameReturnsOnCall[i] = struct {
		result1 []restendpoints.GroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getGroupMembersMutex.RLock()
	defer fake.getGroupMembersMutex.RUnlock()
	fake.getGroupNameMutex.RLock()
	defer fake.getGroupNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGroupsEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ restendpoints.GroupsEndpoint = new(FakeGroupsEndpoint)
