#!/bin/bash

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Navigate to the project root (assuming the script is in the scripts folder)
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Define the output directory for the binaries
OUTPUT_DIR="$PROJECT_ROOT/dist"

# Clean the output directory
echo "Cleaning the output directory..."
rm -rf "$OUTPUT_DIR"

# Create the output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Create an empty checksums.txt file
touch "$OUTPUT_DIR/checksums.txt"

echo ""
echo "Creating binaries for multiple platforms..."
echo "  Building for Windows (64 bit)..."
GOOS=windows GOARCH=amd64 go build -o "$OUTPUT_DIR/ctRestClient-windows-amd64.exe"
sha256sum "$OUTPUT_DIR/ctRestClient-windows-amd64.exe" >> "$OUTPUT_DIR/checksums.txt"

echo "  Building for macOS (Intel)..."
GOOS=darwin GOARCH=amd64 go build -o "$OUTPUT_DIR/ctRestClient-darwin-amd64"
sha256sum "$OUTPUT_DIR/ctRestClient-darwin-amd64" >> "$OUTPUT_DIR/checksums.txt"

echo "  Building for macOS (M1/M2)..."
GOOS=darwin GOARCH=arm64 go build -o "$OUTPUT_DIR/ctRestClient-darwin-arm64"
sha256sum "$OUTPUT_DIR/ctRestClient-darwin-arm64" >> "$OUTPUT_DIR/checksums.txt"

echo "  Building for Linux (64 bit)..."
GOOS=linux GOARCH=amd64 go build -o "$OUTPUT_DIR/ctRestClient-linux-amd64"
sha256sum "$OUTPUT_DIR/ctRestClient-linux-amd64" >> "$OUTPUT_DIR/checksums.txt"

echo "Binaries are located in the $OUTPUT_DIR directory."

echo ""
echo "Creating release archive..."
echo "  Copying LICENSE file..."
cp LICENSE "$OUTPUT_DIR/"

# Get version from git
VERSION="$(git describe --tags --always)"
echo "  Using version: $VERSION"
echo "  Creating VERSION file..."
echo "$VERSION" > "$OUTPUT_DIR/VERSION"
echo "  Compressing archive..."
ARCHIVE_NAME="ctRestClient_${VERSION}.tar.gz"
tar -czf "$OUTPUT_DIR/$ARCHIVE_NAME" \
    -C "$OUTPUT_DIR" \
    "ctRestClient-windows-amd64.exe" \
    "ctRestClient-darwin-amd64" \
    "ctRestClient-darwin-arm64" \
    "ctRestClient-linux-amd64" \
    "LICENSE" \
    "VERSION" \
    "checksums.txt"
echo "Archive is located at $OUTPUT_DIR/$ARCHIVE_NAME"
echo ""
