// Code generated by counterfeiter. DO NOT EDIT.
package restfakes

import (
	"ctRestClient/rest"
	"sync"
)

type FakeGroupsEndpoint struct {
	GetGroupMembersStub        func(int) ([]rest.GroupsMembersResponse, error)
	getGroupMembersMutex       sync.RWMutex
	getGroupMembersArgsForCall []struct {
		arg1 int
	}
	getGroupMembersReturns struct {
		result1 []rest.GroupsMembersResponse
		result2 error
	}
	getGroupMembersReturnsOnCall map[int]struct {
		result1 []rest.GroupsMembersResponse
		result2 error
	}
	GetGroupNamesStub        func([]int) ([]rest.GroupsResponse, error)
	getGroupNamesMutex       sync.RWMutex
	getGroupNamesArgsForCall []struct {
		arg1 []int
	}
	getGroupNamesReturns struct {
		result1 []rest.GroupsResponse
		result2 error
	}
	getGroupNamesReturnsOnCall map[int]struct {
		result1 []rest.GroupsResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGroupsEndpoint) GetGroupMembers(arg1 int) ([]rest.GroupsMembersResponse, error) {
	fake.getGroupMembersMutex.Lock()
	ret, specificReturn := fake.getGroupMembersReturnsOnCall[len(fake.getGroupMembersArgsForCall)]
	fake.getGroupMembersArgsForCall = append(fake.getGroupMembersArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetGroupMembersStub
	fakeReturns := fake.getGroupMembersReturns
	fake.recordInvocation("GetGroupMembers", []interface{}{arg1})
	fake.getGroupMembersMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupsEndpoint) GetGroupMembersCallCount() int {
	fake.getGroupMembersMutex.RLock()
	defer fake.getGroupMembersMutex.RUnlock()
	return len(fake.getGroupMembersArgsForCall)
}

func (fake *FakeGroupsEndpoint) GetGroupMembersCalls(stub func(int) ([]rest.GroupsMembersResponse, error)) {
	fake.getGroupMembersMutex.Lock()
	defer fake.getGroupMembersMutex.Unlock()
	fake.GetGroupMembersStub = stub
}

func (fake *FakeGroupsEndpoint) GetGroupMembersArgsForCall(i int) int {
	fake.getGroupMembersMutex.RLock()
	defer fake.getGroupMembersMutex.RUnlock()
	argsForCall := fake.getGroupMembersArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGroupsEndpoint) GetGroupMembersReturns(result1 []rest.GroupsMembersResponse, result2 error) {
	fake.getGroupMembersMutex.Lock()
	defer fake.getGroupMembersMutex.Unlock()
	fake.GetGroupMembersStub = nil
	fake.getGroupMembersReturns = struct {
		result1 []rest.GroupsMembersResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) GetGroupMembersReturnsOnCall(i int, result1 []rest.GroupsMembersResponse, result2 error) {
	fake.getGroupMembersMutex.Lock()
	defer fake.getGroupMembersMutex.Unlock()
	fake.GetGroupMembersStub = nil
	if fake.getGroupMembersReturnsOnCall == nil {
		fake.getGroupMembersReturnsOnCall = make(map[int]struct {
			result1 []rest.GroupsMembersResponse
			result2 error
		})
	}
	fake.getGroupMembersReturnsOnCall[i] = struct {
		result1 []rest.GroupsMembersResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) GetGroupNames(arg1 []int) ([]rest.GroupsResponse, error) {
	var arg1Copy []int
	if arg1 != nil {
		arg1Copy = make([]int, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.getGroupNamesMutex.Lock()
	ret, specificReturn := fake.getGroupNamesReturnsOnCall[len(fake.getGroupNamesArgsForCall)]
	fake.getGroupNamesArgsForCall = append(fake.getGroupNamesArgsForCall, struct {
		arg1 []int
	}{arg1Copy})
	stub := fake.GetGroupNamesStub
	fakeReturns := fake.getGroupNamesReturns
	fake.recordInvocation("GetGroupNames", []interface{}{arg1Copy})
	fake.getGroupNamesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGroupsEndpoint) GetGroupNamesCallCount() int {
	fake.getGroupNamesMutex.RLock()
	defer fake.getGroupNamesMutex.RUnlock()
	return len(fake.getGroupNamesArgsForCall)
}

func (fake *FakeGroupsEndpoint) GetGroupNamesCalls(stub func([]int) ([]rest.GroupsResponse, error)) {
	fake.getGroupNamesMutex.Lock()
	defer fake.getGroupNamesMutex.Unlock()
	fake.GetGroupNamesStub = stub
}

func (fake *FakeGroupsEndpoint) GetGroupNamesArgsForCall(i int) []int {
	fake.getGroupNamesMutex.RLock()
	defer fake.getGroupNamesMutex.RUnlock()
	argsForCall := fake.getGroupNamesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGroupsEndpoint) GetGroupNamesReturns(result1 []rest.GroupsResponse, result2 error) {
	fake.getGroupNamesMutex.Lock()
	defer fake.getGroupNamesMutex.Unlock()
	fake.GetGroupNamesStub = nil
	fake.getGroupNamesReturns = struct {
		result1 []rest.GroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) GetGroupNamesReturnsOnCall(i int, result1 []rest.GroupsResponse, result2 error) {
	fake.getGroupNamesMutex.Lock()
	defer fake.getGroupNamesMutex.Unlock()
	fake.GetGroupNamesStub = nil
	if fake.getGroupNamesReturnsOnCall == nil {
		fake.getGroupNamesReturnsOnCall = make(map[int]struct {
			result1 []rest.GroupsResponse
			result2 error
		})
	}
	fake.getGroupNamesReturnsOnCall[i] = struct {
		result1 []rest.GroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGroupsEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getGroupMembersMutex.RLock()
	defer fake.getGroupMembersMutex.RUnlock()
	fake.getGroupNamesMutex.RLock()
	defer fake.getGroupNamesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGroupsEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rest.GroupsEndpoint = new(FakeGroupsEndpoint)
