// Code generated by counterfeiter. DO NOT EDIT.
package restfakes

import (
	"ctRestClient/rest"
	"sync"
)

type FakeDynamicGroupsEndpoint struct {
	GetAllDynamicGroupsStub        func() (rest.DynamicGroupsResponse, error)
	getAllDynamicGroupsMutex       sync.RWMutex
	getAllDynamicGroupsArgsForCall []struct {
	}
	getAllDynamicGroupsReturns struct {
		result1 rest.DynamicGroupsResponse
		result2 error
	}
	getAllDynamicGroupsReturnsOnCall map[int]struct {
		result1 rest.DynamicGroupsResponse
		result2 error
	}
	GetGroupStatusStub        func(int) (rest.DynamicGroupsStatusResponse, error)
	getGroupStatusMutex       sync.RWMutex
	getGroupStatusArgsForCall []struct {
		arg1 int
	}
	getGroupStatusReturns struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}
	getGroupStatusReturnsOnCall map[int]struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDynamicGroupsEndpoint) GetAllDynamicGroups() (rest.DynamicGroupsResponse, error) {
	fake.getAllDynamicGroupsMutex.Lock()
	ret, specificReturn := fake.getAllDynamicGroupsReturnsOnCall[len(fake.getAllDynamicGroupsArgsForCall)]
	fake.getAllDynamicGroupsArgsForCall = append(fake.getAllDynamicGroupsArgsForCall, struct {
	}{})
	stub := fake.GetAllDynamicGroupsStub
	fakeReturns := fake.getAllDynamicGroupsReturns
	fake.recordInvocation("GetAllDynamicGroups", []interface{}{})
	fake.getAllDynamicGroupsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDynamicGroupsEndpoint) GetAllDynamicGroupsCallCount() int {
	fake.getAllDynamicGroupsMutex.RLock()
	defer fake.getAllDynamicGroupsMutex.RUnlock()
	return len(fake.getAllDynamicGroupsArgsForCall)
}

func (fake *FakeDynamicGroupsEndpoint) GetAllDynamicGroupsCalls(stub func() (rest.DynamicGroupsResponse, error)) {
	fake.getAllDynamicGroupsMutex.Lock()
	defer fake.getAllDynamicGroupsMutex.Unlock()
	fake.GetAllDynamicGroupsStub = stub
}

func (fake *FakeDynamicGroupsEndpoint) GetAllDynamicGroupsReturns(result1 rest.DynamicGroupsResponse, result2 error) {
	fake.getAllDynamicGroupsMutex.Lock()
	defer fake.getAllDynamicGroupsMutex.Unlock()
	fake.GetAllDynamicGroupsStub = nil
	fake.getAllDynamicGroupsReturns = struct {
		result1 rest.DynamicGroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) GetAllDynamicGroupsReturnsOnCall(i int, result1 rest.DynamicGroupsResponse, result2 error) {
	fake.getAllDynamicGroupsMutex.Lock()
	defer fake.getAllDynamicGroupsMutex.Unlock()
	fake.GetAllDynamicGroupsStub = nil
	if fake.getAllDynamicGroupsReturnsOnCall == nil {
		fake.getAllDynamicGroupsReturnsOnCall = make(map[int]struct {
			result1 rest.DynamicGroupsResponse
			result2 error
		})
	}
	fake.getAllDynamicGroupsReturnsOnCall[i] = struct {
		result1 rest.DynamicGroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatus(arg1 int) (rest.DynamicGroupsStatusResponse, error) {
	fake.getGroupStatusMutex.Lock()
	ret, specificReturn := fake.getGroupStatusReturnsOnCall[len(fake.getGroupStatusArgsForCall)]
	fake.getGroupStatusArgsForCall = append(fake.getGroupStatusArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetGroupStatusStub
	fakeReturns := fake.getGroupStatusReturns
	fake.recordInvocation("GetGroupStatus", []interface{}{arg1})
	fake.getGroupStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusCallCount() int {
	fake.getGroupStatusMutex.RLock()
	defer fake.getGroupStatusMutex.RUnlock()
	return len(fake.getGroupStatusArgsForCall)
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusCalls(stub func(int) (rest.DynamicGroupsStatusResponse, error)) {
	fake.getGroupStatusMutex.Lock()
	defer fake.getGroupStatusMutex.Unlock()
	fake.GetGroupStatusStub = stub
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusArgsForCall(i int) int {
	fake.getGroupStatusMutex.RLock()
	defer fake.getGroupStatusMutex.RUnlock()
	argsForCall := fake.getGroupStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusReturns(result1 rest.DynamicGroupsStatusResponse, result2 error) {
	fake.getGroupStatusMutex.Lock()
	defer fake.getGroupStatusMutex.Unlock()
	fake.GetGroupStatusStub = nil
	fake.getGroupStatusReturns = struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusReturnsOnCall(i int, result1 rest.DynamicGroupsStatusResponse, result2 error) {
	fake.getGroupStatusMutex.Lock()
	defer fake.getGroupStatusMutex.Unlock()
	fake.GetGroupStatusStub = nil
	if fake.getGroupStatusReturnsOnCall == nil {
		fake.getGroupStatusReturnsOnCall = make(map[int]struct {
			result1 rest.DynamicGroupsStatusResponse
			result2 error
		})
	}
	fake.getGroupStatusReturnsOnCall[i] = struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAllDynamicGroupsMutex.RLock()
	defer fake.getAllDynamicGroupsMutex.RUnlock()
	fake.getGroupStatusMutex.RLock()
	defer fake.getGroupStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDynamicGroupsEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rest.DynamicGroupsEndpoint = new(FakeDynamicGroupsEndpoint)
