// Code generated by counterfeiter. DO NOT EDIT.
package restfakes

import (
	"ctRestClient/rest"
	"sync"
)

type FakeDynamicGroupsEndpoint struct {
	GetGroupStatusStub        func(int) (rest.DynamicGroupsStatusResponse, error)
	getGroupStatusMutex       sync.RWMutex
	getGroupStatusArgsForCall []struct {
		arg1 int
	}
	getGroupStatusReturns struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}
	getGroupStatusReturnsOnCall map[int]struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatus(arg1 int) (rest.DynamicGroupsStatusResponse, error) {
	fake.getGroupStatusMutex.Lock()
	ret, specificReturn := fake.getGroupStatusReturnsOnCall[len(fake.getGroupStatusArgsForCall)]
	fake.getGroupStatusArgsForCall = append(fake.getGroupStatusArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetGroupStatusStub
	fakeReturns := fake.getGroupStatusReturns
	fake.recordInvocation("GetGroupStatus", []interface{}{arg1})
	fake.getGroupStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusCallCount() int {
	fake.getGroupStatusMutex.RLock()
	defer fake.getGroupStatusMutex.RUnlock()
	return len(fake.getGroupStatusArgsForCall)
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusCalls(stub func(int) (rest.DynamicGroupsStatusResponse, error)) {
	fake.getGroupStatusMutex.Lock()
	defer fake.getGroupStatusMutex.Unlock()
	fake.GetGroupStatusStub = stub
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusArgsForCall(i int) int {
	fake.getGroupStatusMutex.RLock()
	defer fake.getGroupStatusMutex.RUnlock()
	argsForCall := fake.getGroupStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusReturns(result1 rest.DynamicGroupsStatusResponse, result2 error) {
	fake.getGroupStatusMutex.Lock()
	defer fake.getGroupStatusMutex.Unlock()
	fake.GetGroupStatusStub = nil
	fake.getGroupStatusReturns = struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) GetGroupStatusReturnsOnCall(i int, result1 rest.DynamicGroupsStatusResponse, result2 error) {
	fake.getGroupStatusMutex.Lock()
	defer fake.getGroupStatusMutex.Unlock()
	fake.GetGroupStatusStub = nil
	if fake.getGroupStatusReturnsOnCall == nil {
		fake.getGroupStatusReturnsOnCall = make(map[int]struct {
			result1 rest.DynamicGroupsStatusResponse
			result2 error
		})
	}
	fake.getGroupStatusReturnsOnCall[i] = struct {
		result1 rest.DynamicGroupsStatusResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamicGroupsEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getGroupStatusMutex.RLock()
	defer fake.getGroupStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDynamicGroupsEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rest.DynamicGroupsEndpoint = new(FakeDynamicGroupsEndpoint)
