// Code generated by counterfeiter. DO NOT EDIT.
package csvfakes

import (
	"ctRestClient/config"
	"ctRestClient/csv"
	"encoding/json"
	"sync"
)

type FakeBlockListDataProvider struct {
	BlockListExistsStub        func(config.Group) bool
	blockListExistsMutex       sync.RWMutex
	blockListExistsArgsForCall []struct {
		arg1 config.Group
	}
	blockListExistsReturns struct {
		result1 bool
	}
	blockListExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	IsBlockedStub        func(map[string]json.RawMessage, config.Group) (bool, error)
	isBlockedMutex       sync.RWMutex
	isBlockedArgsForCall []struct {
		arg1 map[string]json.RawMessage
		arg2 config.Group
	}
	isBlockedReturns struct {
		result1 bool
		result2 error
	}
	isBlockedReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBlockListDataProvider) BlockListExists(arg1 config.Group) bool {
	fake.blockListExistsMutex.Lock()
	ret, specificReturn := fake.blockListExistsReturnsOnCall[len(fake.blockListExistsArgsForCall)]
	fake.blockListExistsArgsForCall = append(fake.blockListExistsArgsForCall, struct {
		arg1 config.Group
	}{arg1})
	stub := fake.BlockListExistsStub
	fakeReturns := fake.blockListExistsReturns
	fake.recordInvocation("BlockListExists", []interface{}{arg1})
	fake.blockListExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBlockListDataProvider) BlockListExistsCallCount() int {
	fake.blockListExistsMutex.RLock()
	defer fake.blockListExistsMutex.RUnlock()
	return len(fake.blockListExistsArgsForCall)
}

func (fake *FakeBlockListDataProvider) BlockListExistsCalls(stub func(config.Group) bool) {
	fake.blockListExistsMutex.Lock()
	defer fake.blockListExistsMutex.Unlock()
	fake.BlockListExistsStub = stub
}

func (fake *FakeBlockListDataProvider) BlockListExistsArgsForCall(i int) config.Group {
	fake.blockListExistsMutex.RLock()
	defer fake.blockListExistsMutex.RUnlock()
	argsForCall := fake.blockListExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBlockListDataProvider) BlockListExistsReturns(result1 bool) {
	fake.blockListExistsMutex.Lock()
	defer fake.blockListExistsMutex.Unlock()
	fake.BlockListExistsStub = nil
	fake.blockListExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeBlockListDataProvider) BlockListExistsReturnsOnCall(i int, result1 bool) {
	fake.blockListExistsMutex.Lock()
	defer fake.blockListExistsMutex.Unlock()
	fake.BlockListExistsStub = nil
	if fake.blockListExistsReturnsOnCall == nil {
		fake.blockListExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.blockListExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeBlockListDataProvider) IsBlocked(arg1 map[string]json.RawMessage, arg2 config.Group) (bool, error) {
	fake.isBlockedMutex.Lock()
	ret, specificReturn := fake.isBlockedReturnsOnCall[len(fake.isBlockedArgsForCall)]
	fake.isBlockedArgsForCall = append(fake.isBlockedArgsForCall, struct {
		arg1 map[string]json.RawMessage
		arg2 config.Group
	}{arg1, arg2})
	stub := fake.IsBlockedStub
	fakeReturns := fake.isBlockedReturns
	fake.recordInvocation("IsBlocked", []interface{}{arg1, arg2})
	fake.isBlockedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBlockListDataProvider) IsBlockedCallCount() int {
	fake.isBlockedMutex.RLock()
	defer fake.isBlockedMutex.RUnlock()
	return len(fake.isBlockedArgsForCall)
}

func (fake *FakeBlockListDataProvider) IsBlockedCalls(stub func(map[string]json.RawMessage, config.Group) (bool, error)) {
	fake.isBlockedMutex.Lock()
	defer fake.isBlockedMutex.Unlock()
	fake.IsBlockedStub = stub
}

func (fake *FakeBlockListDataProvider) IsBlockedArgsForCall(i int) (map[string]json.RawMessage, config.Group) {
	fake.isBlockedMutex.RLock()
	defer fake.isBlockedMutex.RUnlock()
	argsForCall := fake.isBlockedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBlockListDataProvider) IsBlockedReturns(result1 bool, result2 error) {
	fake.isBlockedMutex.Lock()
	defer fake.isBlockedMutex.Unlock()
	fake.IsBlockedStub = nil
	fake.isBlockedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockListDataProvider) IsBlockedReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isBlockedMutex.Lock()
	defer fake.isBlockedMutex.Unlock()
	fake.IsBlockedStub = nil
	if fake.isBlockedReturnsOnCall == nil {
		fake.isBlockedReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isBlockedReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeBlockListDataProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.blockListExistsMutex.RLock()
	defer fake.blockListExistsMutex.RUnlock()
	fake.isBlockedMutex.RLock()
	defer fake.isBlockedMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBlockListDataProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ csv.BlockListDataProvider = new(FakeBlockListDataProvider)
