site_name: ctRestClient
site_description: Documentation for ctRestClient
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Home: index.md
  - English Manual: manual-en.md
  - German Manual: manual-de.md
