name: Publish Docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Create MkDocs config
        run: |
          bash .github/scripts/create-mkdocs-config.sh
          
      - name: Build MkDocs site
        run: mkdocs build -d output

      - name: Copy LICENSE to output
        run: cp LICENSE output/

      - name: Push to Target Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CTRESTCLIENT_PUBLISH }}
          external_repository: mvach/ctRestClient
          publish_branch: main
          publish_dir: ./output
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false